// THIS FILE HAS BEEN AUTO-GENERATED BY "graphql-cli-generate-fragments"
// DO NOT EDIT THIS FILE DIRECTLY

export const PostFragment = `fragment Post on Post {
  id
  user {
    ...UserNoNesting
  }
  published
  title
  content {
    ...ContentNoNesting
  }
}
`

export const UserFragment = `fragment User on User {
  id
  name
  email
  password
  posts {
    ...PostNoNesting
  }
}
`

export const ContentFragment = `fragment Content on Content {
  data
}
`


export const PostNoNestingFragment = `fragment PostNoNesting on Post {
  id
  published
  title
}
`

export const UserNoNestingFragment = `fragment UserNoNesting on User {
  id
  name
  email
  password
}
`

export const ContentNoNestingFragment = `fragment ContentNoNesting on Content {
  data
}
`


export const PostDeepNestingFragment = `fragment PostDeepNesting on Post {
  id
  user {
    ...UserDeepNesting
  }
  published
  title
  content {
    ...ContentDeepNesting
  }
}
`

export const UserDeepNestingFragment = `fragment UserDeepNesting on User {
  id
  name
  email
  password
  posts {
    ...PostDeepNesting
  }
}
`

export const ContentDeepNestingFragment = `fragment ContentDeepNesting on Content {
  data
}
`

